version: "3"
services:
  cell-sim7600g-h:
    image: iqtlabs/pibackbone-cell-sim7600g-h:stable
    restart: always
    network_mode: host
    privileged: true
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/gps:/flash/telemetry/gps"
      - "/etc:/etc"
      - "/sys:/sys"
    command:
      - fast.t-mobile.net
      - "300"
  daisy:
    image: iqtlabs/pibackbone-daisy:stable
    restart: always
    network_mode: "none"
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/ais:/flash/telemetry/ais"
    devices:
      - "/dev/serial0:/dev/serial0"
  environment-sensor:
    image: iqtlabs/pibackbone-environment-sensor:stable
    restart: always
    privileged: true
    network_mode: "none"
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/sensors:/flash/telemetry/sensors"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
  hifiberry-dac-plus-adc-pro:
    image: iqtlabs/pibackbone-hifiberry-dac-plus-adc-pro:stable
    restart: always
    network_mode: "none"
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/hydrophone:/flash/telemetry/hydrophone"
    devices:
      - "/dev/snd:/dev/snd"
  pijuice:
    image: iqtlabs/pibackbone-pijuice:stable
    restart: always
    network_mode: "none"
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/power:/flash/telemetry/power"
      - "/var/lib/pijuice:/var/lib/pijuice"
      - "/var/run:/var/run"
      - "/home/pi:/home/pi"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
  s3-upload:
    image: iqtlabs/pibackbone-s3-upload:stable
    restart: always
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "S3_BUCKET=${S3_BUCKET}"
    volumes:
      - "/flash/telemetry:/flash/telemetry"
      - "/flash/s3:/flash/s3"
      - $HOME/.aws:/root/.aws:ro
  status-updater:
    image: iqtlabs/pibackbone-status-updater:stable
    restart: always
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "LOCATION=${LOCATION}"
      - "WEBHOOK_URL=${WEBHOOK_URL}"
    volumes:
      - "/flash:/flash"
      - "/var/run:/var/run"
      - "/var/run/docker.sock:/var/run/docker.sock"
  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "WATCHTOWER_POLL_INTERVAL=3600"
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_INCLUDE_RESTARTING=true"
      - "WATCHTOWER_INCLUDE_STOPPED=true"
      - "WATCHTOWER_REVIVE_STOPPED=true"
