version: "3"
services:
  daisy:
    image: iqtlabs/pibackbone-daisy:stable
    restart: always
    network_mode: "none"
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/ais:/flash/telemetry/ais"
    devices:
      - "/dev/serial0:/dev/serial0"
