version: "3"
services:
  power:
    image: iqtlabs/pibackbone-power:stable
    restart: always
    network_mode: "none"
    environment:
      - "HOSTNAME=${HOSTNAME}"
    volumes:
      - "/flash/telemetry/power:/flash/telemetry/power"
      - "/var/lib/pijuice:/var/lib/pijuice"
      - "/var/run:/var/run"
      - "/home/pi:/home/pi"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
  s3-upload:
    image: iqtlabs/pibackbone-s3-upload:stable
    restart: always
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "S3_BUCKET=${S3_BUCKET}"
    volumes:
      - "/flash/telemetry:/flash/telemetry"
      - "/flash/s3:/flash/s3"
      - $HOME/.aws:/root/.aws:ro
  sense:
    image: iqtlabs/pibackbone-sense:stable
    restart: always
    # TODO find out what it actually needs
    privileged: true
    environment:
      - "HOSTNAME=${HOSTNAME}"
      - "LOCATION=${LOCATION}"
      - "WEBHOOK_URL=${WEBHOOK_URL}"
    volumes:
      - "/flash:/flash"
      - "/var/run:/var/run"
      - "/var/run/docker.sock:/var/run/docker.sock"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
  watchtower:
    image: containrrr/watchtower:armhf-latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "WATCHTOWER_POLL_INTERVAL=3600"
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_INCLUDE_RESTARTING=true"
      - "WATCHTOWER_INCLUDE_STOPPED=true"
      - "WATCHTOWER_REVIVE_STOPPED=true"
