name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: shell_test
      run: |
        wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" && \
        tar --xz -xvf "shellcheck-stable.linux.x86_64.tar.xz" && \
        shellcheck() { "shellcheck-stable/shellcheck" "$@"; } && \
        shellcheck --version && \
        /bin/bash --version && \
        for shellscript in $(find . -type f -name "*.sh"); do /bin/bash -n "$shellscript" && shellcheck -x "$shellscript"; done
    - name: unit_test
      run: |
        pip3 install -r tests/requirements.txt && \
        pip3 install -r requirements.txt && \
        export PYTHONPATH=$PWD/pibackbone:$PYTHONPATH && \
        pytype . && \
        pylint --fail-under=6.0 pibackbone && \
        PATH=/home/runner/.local/bin:$PATH py.test -v -vv --capture=tee-sys --cov-report term-missing --cov=core_services --cov=pibackbone -c .coveragerc && \
        PATH=/home/runner/.local/bin:$PATH coverage report && \
        PATH=/home/runner/.local/bin:$PATH coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      if: github.repository == 'iqtlabs/pibackbone'
